version: "3"
services:
  web:
    image: aibolit:latest
    container_name: aibolit_backend
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/aibolitdb"
    networks:
       - dev
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5433:5432
    expose:
      - 5433
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aibolitdb
    networks:
       - dev

networks:
  dev:
    driver: bridge

volumes:
  postgres:
  app: